<?php

class Config {
    
    private $translations = [
        "tr" => [
            "title" => "Packingo",
            "language" => "Dil",
            "select_file" => "Excel Seç",
            "length_unit" => "Uzunluk Birimi",
            "weight_unit" => "Ağırlık Birimi",
            "container_types" => "Konteyner Tipleri",
            "trailer_types" => "Dorse Tipleri (en az 1 seç)",
            "stackable_src" => "İstiflenebilirlik",
            "stack_excel" => "Excel'den al",
            "stack_yes" => "Tümü istiflenebilir",
            "stack_no" => "Tümü istiflenemez",
            "plan" => "Planla",
            "template" => "Örnek Şablon Oluştur",
            "ready" => "Hazır. Excel seç, tipleri işaretle ve Planla.",
            "must_select_file" => "Lütfen giriş Excel dosyasını seçin.",
            "must_select_trailer" => "En az bir dorse tipi seçmelisiniz.",
            "done" => "Plan tamamlandı.",
            "written_to" => "Çıktı:",
            "err" => "Hata",
            "ok" => "Tamam",
            "info" => "Bilgi",
            "footer" => "Bu yazılım H. DUMAN BOZKURT tarafından geliştirilmiş ve ücretsiz olarak yayınlanmıştır.",
            "units_len" => ["mm", "cm", "m"],
            "units_w" => ["g", "kg", "ton"],
            "must_select_vehicle" => "En az bir dorse veya konteyner tipi seçmelisiniz.",
            "placed" => "Yerleşti",
            "not_fit" => "Sığmıyor",
            "upload_file" => "Excel Dosyası Yükle",
            "supported_formats" => "Desteklenen formatlar: .xlsx, .xls (Maks: 16MB)",
            "how_to_use" => "Nasıl Kullanılır?",
            "tutorial_step1" => "Excel Dosyanızı Hazırlayın",
            "tutorial_step2" => "Dosyayı Yükleyin ve Ayarları Seçin",
            "tutorial_step3" => "Araç Tiplerini Seçin",
            "tutorial_step4" => "Sonuçları İnceleyin ve İndirin",
            "required_columns" => "Gerekli Kolonlar (Tam Header Adları):",
            "important_notes" => "Önemli Notlar:",
            "sample_excel_format" => "Örnek Excel Formatı:",
            "download_sample_excel" => "Örnek Excel İndir",
            "upload_excel_here" => "Excel dosyanızı buraya yükleyin",
            "select_units" => "Ölçü birimlerini seçin",
            "select_stackability" => "İstiflenebilirlik ayarını yapın",
            "choose_vehicle_types" => "İhtiyacınıza uygun araç tiplerini seçin",
            "optimization_summary" => "Optimizasyon Özeti",
            "total_vehicles" => "Toplam Araç",
            "occupancy_rate" => "Doluluk Oranı",
            "total_items" => "Toplam Ürün",
            "vehicle" => "Araç",
            "item_count" => "Ürün Sayısı",
            "weight" => "Ağırlık",
            "occupancy" => "Doluluk",
            "download_options" => "İndirme Seçenekleri",
            "performance" => "Performans",
            "space_saving" => "alan tasarrufu",
            "fewer_vehicles" => "araç daha az",
            "co2_reduction" => "CO₂ emisyonu %23 azaldı",
            "optimal_distribution" => "Optimum yük dağılımı",
            "close" => "Kapat",
            "get_started" => "Hemen Başla!",
            "results_title" => "Optimizasyon Sonuçları",
            "vehicle_details_title" => "Araç Yükleme Detayları",
            "dimensions" => "Boyutlar",
            "max_weight" => "Maks. Ağırlık",
            "used_weight" => "Kullanılan Ağırlık",
            "unplaced_loads" => "Yerleşemeyen Yükler",
            "download_plan_cta" => "Detaylı Planı İndir (Excel)",
            // Tutorial Step 2
            "upload_excel_title" => "📂 Excel Dosyanızı Yükleyin",
            "drag_drop_text" => "Excel dosyanızı buraya sürükleyin veya seçin",
            "supported_formats" => "Desteklenen formatlar: .xlsx, .xls",
            "file_uploaded" => "Dosya Yüklendi",
            "processing" => "İşleniyor...",
            "reading_data" => "Veriler okunuyor",
            "products_found" => "Ürün",
            "successfully_read" => "Başarıyla okundu",
            // Tutorial Step 3
            "select_vehicles_title" => "🚛 Kullanmak İstediğiniz Araçları Seçin",
            "container_types" => "📦 Konteyner Tipleri",
            "trailer_types" => "🚛 Dorse Tipleri",
            "suggestions_title" => "Öneriler:",
            "suggestion_1" => "Yükünüze uygun araç tiplerini seçin",
            "suggestion_2" => "Birden fazla seçenek sistem en iyi kombinasyonu bulur",
            "suggestion_3" => "Ağırlık ve hacim limitlerini kontrol edin",
            // Tutorial Step 4
            "excel_report" => "Excel Raporu İndir",
            "pdf_report" => "PDF Raporu İndir",
            "print_report" => "Yazdır",
            // Column references and important notes
            "column_a" => "A Kolonu",
            "column_b" => "B Kolonu", 
            "column_c" => "C Kolonu",
            "column_d" => "D Kolonu",
            "column_e" => "E Kolonu", 
            "column_f" => "F Kolonu",
            "column_g" => "G Kolonu",
            "note_1" => "İlk satır başlık olmalı",
            "note_2" => "Ölçü birimi sisteme göre ayarlanabilir (mm/cm/m)",
            "note_3" => "Ağırlık birimi sisteme göre ayarlanabilir (kg/ton)",
            "note_4" => "İstiflenebilir: 1=Evet, 0=Hayır",
            "note_5" => "Yük No: Benzersiz numara/kod",
            "note_6" => "Boş satır bırakmayın",
            // Converter translations
            "converter" => "Dönüştürücü",
            "file_converter" => "Dosya Dönüştürücü",
            "container_planner" => "Yük Planlayıcı",
            "select_file_to_convert" => "Dönüştürülecek Dosyayı Seçin",
            "target_format" => "Hedef Format",
            "convert" => "Dönüştür",
            "converting" => "Dönüştürülüyor...",
            "conversion_complete" => "Dönüştürme tamamlandı",
            "download_converted" => "Dönüştürülen Dosyayı İndir",
            "supported_input_formats" => "Desteklenen Giriş Formatları",
            "word_conversions" => "Word Dönüştürme",
            "excel_conversions" => "Excel Dönüştürme", 
            "pdf_conversions" => "PDF Dönüştürme",
            "image_conversions" => "Görsel Dönüştürme",
            "word_to_pdf" => "Word → PDF",
            "word_to_excel" => "Word → Excel",
            "word_to_txt" => "Word → TXT",
            "word_to_image" => "Word → JPG/PNG",
            "excel_to_pdf" => "Excel → PDF",
            "excel_to_word" => "Excel → Word",
            "excel_to_txt" => "Excel → TXT",
            "excel_to_image" => "Excel → JPG/PNG",
            "pdf_to_word" => "PDF → Word",
            "pdf_to_excel" => "PDF → Excel",
            "pdf_to_txt" => "PDF → TXT",
            "pdf_to_image" => "PDF → JPG/PNG",
            "image_to_pdf" => "Görsel → PDF",
            "image_to_word" => "Görsel → Word (OCR)",
            "image_to_excel" => "Görsel → Excel (OCR)",
            "image_to_txt" => "Görsel → TXT (OCR)",
            "jpg_to_png" => "JPG → PNG",
            "png_to_jpg" => "PNG → JPG",
            "conversion_error" => "Dönüştürme hatası",
            "file_not_supported" => "Dosya formatı desteklenmiyor",
            "max_file_size_10mb" => "Maksimum dosya boyutu: 10MB",
        ],
        "en" => [
            "title" => "Packingo",
            "language" => "Language",
            "select_file" => "Select Excel",
            "length_unit" => "Length Unit",
            "weight_unit" => "Weight Unit",
            "container_types" => "Container Types",
            "trailer_types" => "Trailer Types",
            "stackable_src" => "Stackability",
            "stack_excel" => "Use from Excel",
            "stack_yes" => "All stackable",
            "stack_no" => "All non-stackable",
            "plan" => "Plan",
            "template" => "Create Sample Template",
            "ready" => "Ready. Pick Excel, choose types, then Plan.",
            "must_select_file" => "Please select an input Excel file.",
            "must_select_trailer" => "Select at least one trailer type.",
            "done" => "Planning finished.",
            "written_to" => "Output:",
            "err" => "Error",
            "ok" => "OK",
            "info" => "Info",
            "footer" => "This software was developed and released for free by H. DUMAN BOZKURT.",
            "units_len" => ["mm", "cm", "m"],
            "units_w" => ["g", "kg", "ton"],
            "must_select_vehicle" => "You must select at least one trailer or container type.",
            "placed" => "Placed",
            "not_fit" => "Doesn't fit",
            "upload_file" => "Upload Excel file",
            "supported_formats" => "Supported formats: .xlsx, .xls (Max: 16MB)",
            "how_to_use" => "How to Use?",
            "tutorial_step1" => "Prepare Your Excel File",
            "tutorial_step2" => "Upload File and Select Settings",
            "tutorial_step3" => "Choose Vehicle Types",
            "tutorial_step4" => "Review Results and Download",
            "required_columns" => "Required Columns (Exact Header Names):",
            "important_notes" => "Important Notes:",
            "sample_excel_format" => "Sample Excel Format:",
            "download_sample_excel" => "Download Sample Excel",
            "upload_excel_here" => "Upload your Excel file here",
            "select_units" => "Select measurement units",
            "select_stackability" => "Configure stackability setting",
            "choose_vehicle_types" => "Choose vehicle types that suit your needs",
            "optimization_summary" => "Optimization Summary",
            "total_vehicles" => "Total Vehicles",
            "occupancy_rate" => "Occupancy Rate",
            "total_items" => "Total Items",
            "vehicle" => "Vehicle",
            "item_count" => "Item Count",
            "weight" => "Weight",
            "occupancy" => "Occupancy",
            "download_options" => "Download Options",
            "performance" => "Performance",
            "space_saving" => "space saving",
            "fewer_vehicles" => "fewer vehicles",
            "co2_reduction" => "23% CO₂ emission reduction",
            "optimal_distribution" => "Optimal load distribution",
            "close" => "Close",
            "get_started" => "Get Started!",
            "results_title" => "Optimization Results",
            "vehicle_details_title" => "Vehicle Loading Details",
            "dimensions" => "Dimensions",
            "max_weight" => "Max Weight",
            "used_weight" => "Used Weight",
            "unplaced_loads" => "Unplaced Loads",
            "download_plan_cta" => "Download Detailed Plan (Excel)",
            // Tutorial Step 2
            "upload_excel_title" => "📂 Upload Your Excel File",
            "drag_drop_text" => "Drag your Excel file here or select it",
            "supported_formats" => "Supported formats: .xlsx, .xls",
            "file_uploaded" => "File Uploaded",
            "processing" => "Processing...",
            "reading_data" => "Reading data",
            "products_found" => "Products",
            "successfully_read" => "Successfully read",
            // Tutorial Step 3
            "select_vehicles_title" => "🚛 Select Vehicles You Want to Use",
            "container_types" => "📦 Container Types",
            "trailer_types" => "🚛 Trailer Types",
            "suggestions_title" => "Suggestions:",
            "suggestion_1" => "Choose vehicle types suitable for your cargo",
            "suggestion_2" => "Multiple options help system find the best combination",
            "suggestion_3" => "Check weight and volume limits",
            // Tutorial Step 4
            "excel_report" => "Download Excel Report",
            "pdf_report" => "Download PDF Report",
            "print_report" => "Print",
            // Column references and important notes
            "column_a" => "Column A",
            "column_b" => "Column B", 
            "column_c" => "Column C",
            "column_d" => "Column D",
            "column_e" => "Column E", 
            "column_f" => "Column F",
            "column_g" => "Column G",
            "note_1" => "First row must be headers",
            "note_2" => "Unit of measurement can be adjusted (mm/cm/m)",
            "note_3" => "Weight unit can be adjusted (kg/ton)",
            "note_4" => "Stackable: 1=Yes, 0=No",
            "note_5" => "Load No: Unique number/code",
            "note_6" => "Do not leave blank rows",
            // Converter translations
            "converter" => "Converter",
            "file_converter" => "File Converter",
            "container_planner" => "Container Planner",
            "select_file_to_convert" => "Select file to convert",
            "target_format" => "Target Format",
            "convert" => "Convert",
            "converting" => "Converting...",
            "conversion_complete" => "Conversion complete",
            "download_converted" => "Download Converted File",
            "supported_input_formats" => "Supported Input Formats",
            "word_conversions" => "Word Conversions",
            "excel_conversions" => "Excel Conversions", 
            "pdf_conversions" => "PDF Conversions",
            "image_conversions" => "Image Conversions",
            "word_to_pdf" => "Word → PDF",
            "word_to_excel" => "Word → Excel",
            "word_to_txt" => "Word → TXT",
            "word_to_image" => "Word → JPG/PNG",
            "excel_to_pdf" => "Excel → PDF",
            "excel_to_word" => "Excel → Word",
            "excel_to_txt" => "Excel → TXT",
            "excel_to_image" => "Excel → JPG/PNG",
            "pdf_to_word" => "PDF → Word",
            "pdf_to_excel" => "PDF → Excel",
            "pdf_to_txt" => "PDF → TXT",
            "pdf_to_image" => "PDF → JPG/PNG",
            "image_to_pdf" => "Image → PDF",
            "image_to_word" => "Image → Word (OCR)",
            "image_to_excel" => "Image → Excel (OCR)",
            "image_to_txt" => "Image → TXT (OCR)",
            "jpg_to_png" => "JPG → PNG",
            "png_to_jpg" => "PNG → JPG",
            "conversion_error" => "Conversion error",
            "file_not_supported" => "File format not supported",
            "max_file_size_10mb" => "Maximum file size: 10MB",
        ],
        "de" => [
            "title" => "Packingo",
            "language" => "Sprache",
            "select_file" => "Excel wählen",
            "length_unit" => "Längeneinheit",
            "weight_unit" => "Gewichtseinheit",
            "container_types" => "Containertypen",
            "trailer_types" => "Anhängerarten (min. 1 wählen)",
            "stackable_src" => "Stapelbarkeit",
            "stack_excel" => "Aus Excel",
            "stack_yes" => "Alle stapelbar",
            "stack_no" => "Alle nicht stapelbar",
            "plan" => "Planen",
            "template" => "Beispielvorlage erstellen",
            "ready" => "Bereit. Excel wählen, Typen markieren und Planen.",
            "must_select_file" => "Bitte eine Excel-Datei wählen.",
            "must_select_trailer" => "Mindestens einen Anhängertyp wählen.",
            "done" => "Planung abgeschlossen.",
            "written_to" => "Ausgabe:",
            "err" => "Fehler",
            "ok" => "OK",
            "info" => "Info",
            "footer" => "Diese Software wurde von H. DUMAN BOZKURT entwickelt und kostenlos veröffentlicht.",
            "units_len" => ["mm", "cm", "m"],
            "units_w" => ["g", "kg", "ton"],
            "must_select_vehicle" => "Sie müssen mindestens einen Anhänger- oder Containertyp auswählen.",
            "placed" => "Platziert",
            "not_fit" => "Passt nicht",
            "upload_file" => "Excel-Datei hochladen",
            "supported_formats" => "Unterstützte Formate: .xlsx, .xls (Max: 16MB)",
            "how_to_use" => "Wie verwenden?",
            "tutorial_step1" => "Bereiten Sie Ihre Excel-Datei vor",
            "tutorial_step2" => "Datei hochladen und Einstellungen wählen",
            "tutorial_step3" => "Fahrzeugtypen auswählen",
            "tutorial_step4" => "Ergebnisse überprüfen und herunterladen",
            "required_columns" => "Erforderliche Spalten (Genaue Header-Namen):",
            "important_notes" => "Wichtige Hinweise:",
            "sample_excel_format" => "Beispiel Excel Format:",
            "download_sample_excel" => "Beispiel Excel herunterladen",
            "upload_excel_here" => "Laden Sie hier Ihre Excel-Datei hoch",
            "select_units" => "Maßeinheiten auswählen",
            "select_stackability" => "Stapelbarkeit konfigurieren",
            "choose_vehicle_types" => "Wählen Sie Fahrzeugtypen, die Ihren Bedürfnissen entsprechen",
            "optimization_summary" => "Optimierungsübersicht",
            "total_vehicles" => "Fahrzeuge gesamt",
            "occupancy_rate" => "Auslastungsrate",
            "total_items" => "Artikel gesamt",
            "vehicle" => "Fahrzeug",
            "item_count" => "Artikelanzahl",
            "weight" => "Gewicht",
            "occupancy" => "Auslastung",
            "download_options" => "Download-Optionen",
            "performance" => "Leistung",
            "space_saving" => "Platzeinsparung",
            "fewer_vehicles" => "weniger Fahrzeuge",
            "co2_reduction" => "23% CO₂-Emissionsreduktion",
            "optimal_distribution" => "Optimale Lastverteilung",
            "close" => "Schließen",
            "get_started" => "Loslegen!",
            "results_title" => "Optimierungsergebnisse",
            "vehicle_details_title" => "Fahrzeugbeladungsdetails",
            "dimensions" => "Abmessungen",
            "max_weight" => "Max. Gewicht",
            "used_weight" => "Verwendetes Gewicht",
            "unplaced_loads" => "Nicht platzierte Lasten",
            "download_plan_cta" => "Detailplan herunterladen (Excel)",
            // Tutorial Step 2
            "upload_excel_title" => "📂 Laden Sie Ihre Excel-Datei hoch",
            "drag_drop_text" => "Ziehen Sie Ihre Excel-Datei hierher oder wählen Sie sie aus",
            "supported_formats" => "Unterstützte Formate: .xlsx, .xls",
            "file_uploaded" => "Datei hochgeladen",
            "processing" => "Verarbeitung...",
            "reading_data" => "Daten werden gelesen",
            "products_found" => "Produkte",
            "successfully_read" => "Erfolgreich gelesen",
            // Tutorial Step 3
            "select_vehicles_title" => "🚛 Wählen Sie Fahrzeuge aus, die Sie verwenden möchten",
            "container_types" => "📦 Container-Typen",
            "trailer_types" => "🚛 Anhänger-Typen",
            "suggestions_title" => "Vorschläge:",
            "suggestion_1" => "Wählen Sie für Ihre Fracht geeignete Fahrzeugtypen",
            "suggestion_2" => "Mehrere Optionen helfen dem System, die beste Kombination zu finden",
            "suggestion_3" => "Überprüfen Sie Gewichts- und Volumengrenzen",
            // Tutorial Step 4
            "excel_report" => "Excel-Bericht herunterladen",
            "pdf_report" => "PDF-Bericht herunterladen",
            "print_report" => "Drucken",
            // Column references and important notes
            "column_a" => "Spalte A",
            "column_b" => "Spalte B", 
            "column_c" => "Spalte C",
            "column_d" => "Spalte D",
            "column_e" => "Spalte E", 
            "column_f" => "Spalte F",
            "column_g" => "Spalte G",
            "note_1" => "Erste Zeile muss Kopfzeile sein",
            "note_2" => "Maßeinheit kann angepasst werden (mm/cm/m)",
            "note_3" => "Gewichtseinheit kann angepasst werden (kg/ton)",
            "note_4" => "Stapelbar: 1=Ja, 0=Nein",
            "note_5" => "Ladungs-Nr.: Eindeutige Nummer/Code",
            "note_6" => "Keine leeren Zeilen lassen",
            // Converter translations
            "converter" => "Konverter",
            "file_converter" => "Datei-Konverter",
            "container_planner" => "Container-Planer",
            "select_file_to_convert" => "Datei zum Konvertieren auswählen",
            "target_format" => "Zielformat",
            "convert" => "Konvertieren",
            "converting" => "Konvertiert...",
            "conversion_complete" => "Konvertierung abgeschlossen",
            "download_converted" => "Konvertierte Datei herunterladen",
            "supported_input_formats" => "Unterstützte Eingabeformate",
            "word_conversions" => "Word-Konvertierungen",
            "excel_conversions" => "Excel-Konvertierungen", 
            "pdf_conversions" => "PDF-Konvertierungen",
            "image_conversions" => "Bild-Konvertierungen",
            "word_to_pdf" => "Word → PDF",
            "word_to_excel" => "Word → Excel",
            "word_to_txt" => "Word → TXT",
            "word_to_image" => "Word → JPG/PNG",
            "excel_to_pdf" => "Excel → PDF",
            "excel_to_word" => "Excel → Word",
            "excel_to_txt" => "Excel → TXT",
            "excel_to_image" => "Excel → JPG/PNG",
            "pdf_to_word" => "PDF → Word",
            "pdf_to_excel" => "PDF → Excel",
            "pdf_to_txt" => "PDF → TXT",
            "pdf_to_image" => "PDF → JPG/PNG",
            "image_to_pdf" => "Bild → PDF",
            "image_to_word" => "Bild → Word (OCR)",
            "image_to_excel" => "Bild → Excel (OCR)",
            "image_to_txt" => "Bild → TXT (OCR)",
            "jpg_to_png" => "JPG → PNG",
            "png_to_jpg" => "PNG → JPG",
            "conversion_error" => "Konvertierungsfehler",
            "file_not_supported" => "Dateiformat nicht unterstützt",
            "max_file_size_10mb" => "Maximale Dateigröße: 10MB",
        ]
    ];

    // Unit conversion factors
    private $lengthFactors = ["mm" => 1, "cm" => 10, "m" => 1000];
    private $weightFactors = ["g" => 0.001, "kg" => 1, "ton" => 1000];

    // Container specifications (internal dimensions in mm)
    private $containers = [
        "20' Dry (20DC / 20GP)" => ["iL" => 5898, "iW" => 2352, "iH" => 2393, "max_kg" => 21700, "cost" => 24000],
        "40' Dry (40DC / 40GP)" => ["iL" => 12032, "iW" => 2352, "iH" => 2393, "max_kg" => 26500, "cost" => 36000],
        "40' High Cube (40HC)" => ["iL" => 12032, "iW" => 2352, "iH" => 2698, "max_kg" => 26500, "cost" => 38000],
        "45' High Cube (45HC)" => ["iL" => 13556, "iW" => 2352, "iH" => 2698, "max_kg" => 30000, "cost" => 44000],
        "20' Open Top (20OT)" => ["iL" => 5898, "iW" => 2352, "iH" => 2393, "max_kg" => 21700, "cost" => 26000],
        "40' Open Top (40OT)" => ["iL" => 12032, "iW" => 2352, "iH" => 2393, "max_kg" => 26500, "cost" => 40000],
        "20' Flat Rack (20FR)" => ["iL" => 5980, "iW" => 2440, "iH" => 2400, "max_kg" => 31000, "cost" => 30000],
        "40' Flat Rack (40FR)" => ["iL" => 12032, "iW" => 2440, "iH" => 2590, "max_kg" => 45000, "cost" => 50000],
    ];

    // Trailer specifications (internal dimensions in mm)
    private $trailers = [
        "Standart Tır" => ["iL" => 13560, "iW" => 2460, "iH" => 2700, "max_kg" => 25500, "cost" => 35000],
        "Flatbed" => ["iL" => 14500, "iW" => 3450, "iH" => 3350, "max_kg" => 27000, "cost" => 40000],
        "Lowbed" => ["iL" => 25000, "iW" => 5700, "iH" => 4200, "max_kg" => 70000, "cost" => 55000],
    ];

    public function getTranslations($lang = 'en') {
        return $this->translations[$lang] ?? $this->translations['en'];
    }

    public function getLengthFactors() {
        return $this->lengthFactors;
    }

    public function getWeightFactors() {
        return $this->weightFactors;
    }

    public function getContainers() {
        return $this->containers;
    }

    public function getTrailers() {
        return $this->trailers;
    }

    public function getAllVehicleTypes() {
        return array_merge($this->containers, $this->trailers);
    }
}